//inventory
export const ADD_INV_ITEM = 'ADD_INV_ITEM'
export const EDIT_INV_ITEM = 'EDIT_INV_ITEM'
export const CHECK_FOR_DELETE = 'CHECK_FOR_DELETE'
export const DELETE_INV_GROUP = 'DELETE_INV_GROUP'
export const SEND_TO_SHOPPING_LIST = 'SEND_TO_SHOPPING_LIST'
export const SORT_INV_BY_NAME = 'SORT_INV_BY_NAME'
export const SORT_INV_BY_AMOUNT = 'SORT_INV_BY_AMOUNT'
export const REPLENISH = 'REPLENISH'
export const SET_INITIAL_DATA = 'SET_INITIAL_DATA'

//shopping
export const ADD_SHOP_ITEM = 'ADD_SHOP_ITEM'
export const EDIT_SHOP_ITEM = 'EDIT_SHOP_ITEM'
export const DELETE_SHOP_ITEM = 'DELETE_SHOP_ITEM'
export const MARK_COMPLETED = 'MARK_COMPLETED'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const CHECK_FOR_SHOP_DELETE = 'CHECK_FOR_SHOP_DELETE'
export const SET_INITIAL_SHOPPING_DATA = 'SET_INITIAL_SHOPPING_DATA'

//recipes
export const GET_RECIPES = 'GET_RECIPES'
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES'
export const UPDATE_DETAIL_RECIPE = 'UPDATE_DETAIL_RECIPE'
export const SET_BREAKFAST_DATA = 'SET_BREAKFAST_DATA'
export const SET_LUNCH_DATA = 'SET_LUNCH_DATA'
export const SET_DINNER_DATA = 'SET_DINNER_DATA'
export const SET_DESSERT_DATA = 'SET_DESSERT_DATA'
export const UPDATE_RECIPE_SEARCH = 'UPDATE_RECIPE_SEARCH'
export const UPDATE_SEARCHED_FLAG = 'UPDATE_SEARCHED_FLAG'
export const ADD_FAV = 'ADD_FAV'
export const REMOVE_FAV = 'REMOVE_FAV'
export const SET_INSTOCK_SEARCH_DATA = 'SET_INSTOCK_SEARCH_DATA'
export const SET_SINGLE_RECIPE_DATA = 'SET_SINGLE_RECIPE_DATA'
export const SET_INITIAL_FAV_DATA = 'SET_INITIAL_FAV_DATA'

//mealplanning
export const ADD_MEAL_ITEM = 'ADD_ITEM'
export const EDIT_MEAL_ITEM = 'EDIT_ITEM'
export const DELETE_MEAL_ITEM = 'DELETE_MEAL_ITEM'
export const DELETE_MEAL = 'DELETE_MEAL'
export const ADD_RECIPE_ITEM = 'ADD_RECIPE_ITEM'
export const UPDATE_DATE_MEAL = 'UPDATE_DATE_MEAL'
export const SET_INITIAL_MEAL_DATA = 'SET_INITIAL_MEAL_DATA'

//shopping list filters
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_ACTIVE = 'SHOW_ACTIVE'
export const SHOW_COMPLETED = 'SHOW_COMPLETED'