export const refItems = [
      'vanilla',
      'vanilla extract',
      'bread',
      'flour',
      'sugar',
      'brown sugar',
      'milk',
      'egg',
      'eggs',
      'salt',
      'cilantro',
      'ginger',
      'orange',
      'oranges',
      'lemon',
      'lemons',
      'parsley',
      'rice vinegar',
      'thyme',
      'dijon',
      'dijon mustard',
      'rosemary',
      'chicken breasts',
      'ground beef',
      'mayo',
      'cranberries',
      'paprika',
      'butter',
      'mint',
      'onion',
      'coriander',
      'cumin',
      'jalapeno',
      'jalapenos',
      'chocolate chips',
      'cinnamon',
      'cloves',
      'nutmeg',
      'pepper',
      'bread flour',
      'all purpose flour',
      'all-purpose flour'
    ]

export const refItemsToAdd = [
        'vanilla extract',
        'vanilla',
        ['wheat bread','white bread','multi-grain bread'],
        ['bread flour','all purpose flour','all-purpose flour','whole wheat flour'],
        ['granulated sugar','white sugar'],
        ['light brown sugar','dark brown sugar'],
        ['whole milk','skim milk'],
        'eggs',
        'egg',
        ['sea salt','kosher salt','coarse kosher salt'],
        ['fresh cilantro','fresh cilantro leaves','dried cilantro'],
        ['fresh ginger','ground ginger'],
        ['oranges','orange peel','orange zest'],
        ['orange','orange peel','orange zest'],
        ['lemons','lemon zest'],
        ['lemon zest','lemon'],
        ['fresh parsley','dried parsley'],
        'unseasoned rice vinegar',
        ['fresh thyme','dried thyme'],
        ['dijon mustard','spicy mustard','brown mustard'],
        ['dijon','spicy mustard','brown mustard'],
        'fresh rosemary',
        ['baked chicken breast','boneless chicken breasts','boneless skinless chicken breasts'],
        'ground turkey',
        'mayonnaise',
        'dried cranberries',
        'smoked paprika',
        'unsalted butter',
        'mint leaves',
        ['yellow onion','sweet onion','vadilia onion','onions'],
        'ground coriander',
        'ground cumin',
        ['pickled jalepeno','pickled jalepenos'],
        ['pickled jalepeno','pickled jalepenos'],
        'semi sweet chocolate chips',
        'ground cinnamon',
        'ground cloves',
        'ground nutmeg',
        ['black pepper','ground black pepper']
        ['flour','all purpose flour','all-purpose flour','whole wheat flour'],
        ['bread flour','flour','all-purpose flour','whole wheat flour'],
        ['bread flour','all purpose flour','flour','whole wheat flour'],
      ]